# These are supported funding model platforms

patreon: alphaws
custom: ["https://twitter.com/alphaws", "https://www.prstart.hu", "https://www.prstart.co.uk", "https://www.gofundme.com/f/marcells-medical-expenses"]
