version: '3'
services:
  app:
    image: node:16
    container_name: dicrypto
    restart: unless-stopped
    volumes:
      - ./:/node/app
    command:
      - /node/app/start.sh
    working_dir: /node/app

  restarter:
    image: docker
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 3000; docker restart dicrypto; done" ]
    restart: unless-stopped